name: Android Compiler
on: [pull_request, push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
     
    - name: Use Java8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8

    #- name: Download Compiler
    #  run: git clone https://github.com/graysuit/b4a_compiler 
    #  
    #- name: Copy Compiler
    #  run: xcopy b4a "" /h /i /c /k /e /r /y  
    #  
    - name: Build APK
      working-directory: ./android
      run: cmd /c compile.bat "anti_vm.apk"
      
    - name: Build APK
      working-directory: ./android
      run: cmd /c dir & cd b4a & B4ABuilder.exe -Task=build 
