name: Compiler
on: [push]
env:
  csc: C:/Windows/Microsoft.NET/Framework/v2.0.50727/csc.exe
  
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: env.csc -target:winexe Universal_VM_Detector.cs

    - name: Upload
      uses: actions/upload-artifact@v1.0.0
      with:
       name: Release
       path: Universal_VM_Detector.exe
