name: Compiler
on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cmd.exe /c cd windows & C:\Windows\Microsoft.NET\Framework\v2.0.50727\csc.exe -target:winexe anti-vm.cs

    - name: Upload
      uses: actions/upload-artifact@v1.0.0
      with:
       name: Release
       path: "windows/anti-vm.exe"
